### ISSUE TITLE
Fix html entities

### ISSUE THREAD

**Issue by kajusK** [fkolacek/ClapTrap#1]
ClapTrap should translate html entities to appropriate characters:

[&quot;We Love Raleigh&quot; - A Red Hat music video - YouTube]

**Comment by fkolacek** [comment]
Fixed in [f9bbc956e321b39a7dd608e81890327ff69f2c8b](https://github.com/fkolacek/ClapTrap/commit/f9bbc956e321b39a7dd608e81890327ff69f2c8b)

**Comment by fkolacek** [comment]
Fixed in [f9bbc956e321b39a7dd608e81890327ff69f2c8b](https://github.com/fkolacek/ClapTrap/commit/f9bbc956e321b39a7dd608e81890327ff69f2c8b)
